/* SFX Library — client-side app.
 * Reads window.__SFX_MANIFEST__ (generated by scan.mjs). Preview with waveform + dB
 * readouts, download, favorite, bulk-tag, sort, and filter by game / length / tags.
 * Tags + favorites persist in localStorage and export to data/library-data.json.
 */
(() => {
  'use strict';

  const TAGS_KEY = 'sfx_tags_v1';        // { [soundId]: string[] }
  const FAV_KEY = 'sfx_favs_v1';         // [ soundId, ... ]
  const ANALYSIS_KEY = 'sfx_analysis_v1';// { [soundId]: {duration,peakDb,rmsDb,peaks} } browser-measured cache
  const DATA_FILE = 'data/library-data.json';

  const LENGTH_BUCKETS = [
    { id: 'tiny',   label: 'Tiny (<0.5s)',    min: 0,   max: 0.5 },
    { id: 'short',  label: 'Short (0.5–1s)',  min: 0.5, max: 1 },
    { id: 'medium', label: 'Medium (1–3s)',   min: 1,   max: 3 },
    { id: 'long',   label: 'Long (3–10s)',    min: 3,   max: 10 },
    { id: 'xlong',  label: 'Very long (>10s)', min: 10, max: Infinity },
  ];

  const manifest = window.__SFX_MANIFEST__ || { sounds: [], games: [] };
  const sounds = manifest.sounds || [];
  const soundById = new Map(sounds.map((s) => [s.id, s]));

  // ---- persisted state ----
  let tagStore = loadJSON(TAGS_KEY, {});
  let favorites = new Set(loadJSON(FAV_KEY, []));
  const analysisCache = loadJSON(ANALYSIS_KEY, {});

  // ---- resolved analysis per sound (manifest wins, else cache, else null) ----
  const analysis = {};
  for (const s of sounds) {
    if (s.peaks || s.duration != null) {
      analysis[s.id] = { duration: s.duration, peakDb: s.peakDb, rmsDb: s.rmsDb, peaks: s.peaks || null };
    } else if (analysisCache[s.id]) {
      analysis[s.id] = analysisCache[s.id];
    } else {
      analysis[s.id] = { duration: null, peakDb: null, rmsDb: null, peaks: null };
    }
  }

  // ---- transient UI state ----
  const filters = { search: '', games: new Set(), lengths: new Set(), tags: new Set(), tagMatchAll: false, favOnly: false };
  let sortMode = 'name-asc';
  const selection = new Set();
  const cardEls = new Map(); // id -> { root, waveCanvas, peakPill, rmsPill, durPill, star, checkbox, tagsWrap }

  // ---- element refs ----
  const el = id => document.getElementById(id);
  const dom = {
    grid: el('grid'), empty: el('empty-state'), noManifest: el('no-manifest'),
    countBadge: el('count-badge'), resultsInfo: el('results-info'),
    filterGames: el('filter-games'), filterLengths: el('filter-lengths'),
    filterTags: el('filter-tags'), noTagsHint: el('no-tags-hint'),
    search: el('search'), sort: el('sort'), tagMatchMode: el('tag-match-mode'),
    clearBtn: el('clear-filters'), exportBtn: el('export-btn'), importInput: el('import-input'),
    favToggle: el('fav-toggle'), favCount: el('fav-count'), suggestions: el('tag-suggestions'),
    bulkBar: el('bulk-bar'), bulkCount: el('bulk-count'), bulkTagInput: el('bulk-tag-input'),
    bulkAdd: el('bulk-add'), bulkRemove: el('bulk-remove'), bulkStar: el('bulk-star'),
    bulkUnstar: el('bulk-unstar'), bulkSelectVisible: el('bulk-select-visible'), bulkClear: el('bulk-clear'),
    // sync
    syncStatus: el('sync-status'), syncBtn: el('sync-btn'), syncModal: el('sync-modal'),
    syncClose: el('sync-close'), syncConnectView: el('sync-connect-view'), syncConnectedView: el('sync-connected-view'),
    gistToken: el('gist-token'), gistId: el('gist-id'), gistConnect: el('gist-connect'),
    syncError: el('sync-error'), gistLink: el('gist-link'), gistSyncNow: el('gist-sync-now'),
    gistPull: el('gist-pull'), gistDisconnect: el('gist-disconnect'),
  };

  // ================= helpers =================
  function loadJSON(key, fallback) {
    try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch { return fallback; }
  }
  function saveJSON(key, val) { try { localStorage.setItem(key, JSON.stringify(val)); } catch {} }
  function saveTags() { saveJSON(TAGS_KEY, tagStore); markDirty(); }
  function saveFavs() { saveJSON(FAV_KEY, [...favorites]); markDirty(); }
  function tagsFor(id) { return tagStore[id] || []; }
  function durOf(id) { return analysis[id] ? analysis[id].duration : null; }
  function bucketFor(id) {
    const d = durOf(id);
    if (d == null) return null;
    return LENGTH_BUCKETS.find((b) => d >= b.min && d < b.max) || null;
  }
  function allCustomTags() {
    const set = new Set();
    for (const id in tagStore) for (const t of tagStore[id]) set.add(t);
    return [...set].sort((a, b) => a.localeCompare(b));
  }
  function fmtDuration(d) {
    if (d == null) return '—';
    if (d >= 60) { const m = Math.floor(d / 60); const s = Math.round(d % 60).toString().padStart(2, '0'); return `${m}m ${s}s`; }
    return `${d.toFixed(2)}s`;
  }
  function fmtSize(b) {
    if (!b) return '';
    if (b < 1024) return `${b} B`;
    if (b < 1048576) return `${(b / 1024).toFixed(0)} KB`;
    return `${(b / 1048576).toFixed(1)} MB`;
  }
  function fmtDb(v) { return v == null ? '—' : `${v.toFixed(1)} dB`; }
  function escapeHtml(str) {
    return String(str).replace(/[&<>"']/g, (m) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[m]));
  }

  // ================= filtering + sorting =================
  function matches(s) {
    if (filters.favOnly && !favorites.has(s.id)) return false;
    if (filters.search && !s.name.toLowerCase().includes(filters.search)) return false;
    if (filters.games.size && !filters.games.has(s.game)) return false;
    if (filters.lengths.size) { const b = bucketFor(s.id); if (!b || !filters.lengths.has(b.id)) return false; }
    if (filters.tags.size) {
      const st = new Set(tagsFor(s.id));
      if (filters.tagMatchAll) { for (const t of filters.tags) if (!st.has(t)) return false; }
      else { let any = false; for (const t of filters.tags) if (st.has(t)) { any = true; break; } if (!any) return false; }
    }
    return true;
  }
  function sortSounds(list) {
    const num = (v) => (v == null ? -Infinity : v);
    const by = {
      'name-asc': (a, b) => a.name.localeCompare(b.name),
      'name-desc': (a, b) => b.name.localeCompare(a.name),
      'dur-asc': (a, b) => num(durOf(a.id)) - num(durOf(b.id)),
      'dur-desc': (a, b) => num(durOf(b.id)) - num(durOf(a.id)),
      'peak-desc': (a, b) => num(analysis[b.id].peakDb) - num(analysis[a.id].peakDb),
      'peak-asc': (a, b) => num(analysis[a.id].peakDb) - num(analysis[b.id].peakDb),
      'size-asc': (a, b) => (a.size || 0) - (b.size || 0),
      'size-desc': (a, b) => (b.size || 0) - (a.size || 0),
      'game-asc': (a, b) => a.game.localeCompare(b.game) || a.name.localeCompare(b.name),
    }[sortMode] || ((a, b) => 0);
    return [...list].sort(by);
  }

  // ================= sidebar filters =================
  function renderFilters() {
    dom.filterGames.innerHTML = '';
    (manifest.games || []).forEach((g) => {
      const n = sounds.filter((s) => s.game === g).length;
      dom.filterGames.appendChild(chip(g, n, filters.games.has(g), () => toggleFilter(filters.games, g)));
    });
    dom.filterLengths.innerHTML = '';
    LENGTH_BUCKETS.forEach((b) => {
      const n = sounds.filter((s) => { const bb = bucketFor(s.id); return bb && bb.id === b.id; }).length;
      dom.filterLengths.appendChild(chip(b.label, n, filters.lengths.has(b.id), () => toggleFilter(filters.lengths, b.id)));
    });
    const tags = allCustomTags();
    dom.filterTags.innerHTML = '';
    dom.noTagsHint.hidden = tags.length > 0;
    tags.forEach((t) => {
      const n = sounds.filter((s) => tagsFor(s.id).includes(t)).length;
      dom.filterTags.appendChild(chip(t, n, filters.tags.has(t), () => toggleFilter(filters.tags, t)));
    });
    dom.favCount.textContent = favorites.size;
    dom.favToggle.classList.toggle('active', filters.favOnly);
    renderSuggestions();
  }
  function chip(label, count, active, onClick) {
    const d = document.createElement('div');
    d.className = 'chip' + (active ? ' active' : '');
    d.innerHTML = `${escapeHtml(label)}<span class="chip-count">${count}</span>`;
    d.addEventListener('click', onClick);
    return d;
  }
  function toggleFilter(set, val) { set.has(val) ? set.delete(val) : set.add(val); render(); }
  function renderSuggestions() {
    dom.suggestions.innerHTML = allCustomTags().map((t) => `<option value="${escapeHtml(t)}">`).join('');
  }

  // ================= grid =================
  function render() { renderFilters(); renderGrid(); }

  function renderGrid() {
    const visible = sortSounds(sounds.filter(matches));
    cardEls.clear();
    dom.grid.innerHTML = '';
    dom.countBadge.textContent = `${sounds.length} sound${sounds.length === 1 ? '' : 's'}`;
    dom.noManifest.hidden = sounds.length > 0;
    dom.empty.hidden = visible.length > 0 || sounds.length === 0;
    dom.resultsInfo.textContent = sounds.length ? `Showing ${visible.length} of ${sounds.length}` : '';

    const frag = document.createDocumentFragment();
    for (const s of visible) frag.appendChild(buildCard(s));
    dom.grid.appendChild(frag);
    // Draw now that canvases are attached (reading clientWidth forces the needed layout).
    for (const s of visible) drawWaveform(s.id, 0);
  }

  function buildCard(s) {
    const a = analysis[s.id];
    const root = document.createElement('div');
    root.className = 'card' + (selection.has(s.id) ? ' selected' : '');

    // header: checkbox + name + star
    const head = document.createElement('div');
    head.className = 'card-head';
    const checkbox = document.createElement('input');
    checkbox.type = 'checkbox';
    checkbox.className = 'card-check';
    checkbox.checked = selection.has(s.id);
    checkbox.title = 'Select for bulk actions';
    checkbox.addEventListener('change', () => toggleSelect(s.id, checkbox.checked));
    const name = document.createElement('div');
    name.className = 'card-name';
    name.textContent = s.name;
    const star = document.createElement('button');
    star.className = 'star' + (favorites.has(s.id) ? ' on' : '');
    star.textContent = favorites.has(s.id) ? '★' : '☆';
    star.title = 'Favorite';
    star.addEventListener('click', () => toggleFav(s.id));
    head.append(checkbox, name, star);

    // meta pills
    const meta = document.createElement('div');
    meta.className = 'card-meta';
    const durPill = pill(fmtDuration(a.duration));
    const peakPill = pill('pk ' + fmtDb(a.peakDb), 'db');
    const rmsPill = pill('rms ' + fmtDb(a.rmsDb), 'db');
    applyPeakColor(peakPill, a.peakDb);
    meta.append(pill(s.game, 'game'), durPill, peakPill, rmsPill, pill(s.ext.toUpperCase()));
    if (s.size) meta.append(pill(fmtSize(s.size)));

    // waveform
    const waveCanvas = document.createElement('canvas');
    waveCanvas.className = 'waveform';
    waveCanvas.height = 56;
    waveCanvas.addEventListener('click', (e) => {
      const dur = analysis[s.id].duration;
      if (!dur) return;
      const rect = waveCanvas.getBoundingClientRect();
      audio.currentTime = Math.max(0, Math.min(dur, ((e.clientX - rect.left) / rect.width) * dur));
      if (audio.paused) audio.play().catch(() => {});
    });

    // audio
    const audio = document.createElement('audio');
    audio.controls = true;
    audio.preload = 'none';
    audio.src = s.src;
    audio.addEventListener('timeupdate', () => {
      const dur = analysis[s.id].duration;
      drawWaveform(s.id, dur ? audio.currentTime / dur : 0);
    });
    audio.addEventListener('ended', () => drawWaveform(s.id, 0));
    // Non-WAV: measure metadata for duration if we have none yet (works over file://).
    if (a.duration == null) audio.addEventListener('loadedmetadata', () => {
      if (analysis[s.id].duration == null && isFinite(audio.duration)) {
        analysis[s.id].duration = Math.round(audio.duration * 1000) / 1000;
        updateCardMeta(s.id);
      }
    });

    // actions
    const actions = document.createElement('div');
    actions.className = 'card-actions';
    const dl = document.createElement('a');
    dl.className = 'download';
    dl.href = s.src; dl.download = s.name + '.' + s.ext; dl.textContent = '⬇ Download';
    actions.appendChild(dl);

    // tags
    const tagsWrap = document.createElement('div');
    tagsWrap.className = 'card-tags';

    root.append(head, meta, waveCanvas, audio, actions, tagsWrap);
    cardEls.set(s.id, { root, waveCanvas, peakPill, rmsPill, durPill, star, checkbox, tagsWrap });
    renderCardTags(s.id);
    return root;
  }

  function pill(text, cls) {
    const span = document.createElement('span');
    span.className = 'pill' + (cls ? ' ' + cls : '');
    span.textContent = text;
    return span;
  }
  function applyPeakColor(pillEl, peakDb) {
    pillEl.classList.remove('hot', 'warm');
    if (peakDb == null) return;
    if (peakDb >= -1) pillEl.classList.add('hot');       // near/at clipping
    else if (peakDb >= -3) pillEl.classList.add('warm'); // very hot
  }

  // Update meta pills in place (after async duration/analysis) without rebuilding the card.
  function updateCardMeta(id) {
    const refs = cardEls.get(id);
    if (!refs) return;
    const a = analysis[id];
    refs.durPill.textContent = fmtDuration(a.duration);
    refs.peakPill.textContent = 'pk ' + fmtDb(a.peakDb);
    refs.rmsPill.textContent = 'rms ' + fmtDb(a.rmsDb);
    applyPeakColor(refs.peakPill, a.peakDb);
  }

  // ================= waveform drawing =================
  const WAVE_CSS_H = 56; // logical height in CSS px (must match .waveform height)
  function drawWaveform(id, progress) {
    const refs = cardEls.get(id);
    if (!refs) return;
    const canvas = refs.waveCanvas;
    const peaks = analysis[id].peaks;
    const cssW = canvas.clientWidth || 260;
    const dpr = window.devicePixelRatio || 1;
    const targetW = Math.round(cssW * dpr), targetH = Math.round(WAVE_CSS_H * dpr);
    if (canvas.width !== targetW) canvas.width = targetW;   // assigning width/height also clears the canvas
    if (canvas.height !== targetH) canvas.height = targetH;
    const ctx = canvas.getContext('2d');
    const W = canvas.width, H = canvas.height;
    ctx.clearRect(0, 0, W, H);

    if (!peaks || !peaks.length) {
      ctx.strokeStyle = 'rgba(154,163,178,0.4)';
      ctx.beginPath(); ctx.moveTo(0, H / 2); ctx.lineTo(W, H / 2); ctx.stroke();
      return;
    }
    const max = Math.max(0.0001, ...peaks); // normalize to own peak for visible shape
    const n = peaks.length;
    const barW = W / n;
    const playedX = progress * W;
    const mid = H / 2;
    for (let i = 0; i < n; i++) {
      const h = (peaks[i] / max) * (H * 0.92);
      const x = i * barW;
      ctx.fillStyle = (x < playedX) ? '#6c8cff' : 'rgba(154,163,178,0.55)';
      ctx.fillRect(x, mid - h / 2, Math.max(1, barW - 0.6), h);
    }
  }

  // ================= tags on card =================
  function renderCardTags(id) {
    const refs = cardEls.get(id);
    if (!refs) return;
    const wrap = refs.tagsWrap;
    wrap.innerHTML = '';
    for (const t of tagsFor(id)) {
      const tag = document.createElement('span');
      tag.className = 'tag';
      tag.innerHTML = `${escapeHtml(t)} <button title="Remove tag" aria-label="Remove tag">×</button>`;
      tag.querySelector('button').addEventListener('click', () => removeTag(id, t));
      wrap.appendChild(tag);
    }
    const addBtn = document.createElement('button');
    addBtn.className = 'tag-add'; addBtn.textContent = '+'; addBtn.title = 'Add tag';
    addBtn.addEventListener('click', () => startAddTag(id, wrap, addBtn));
    wrap.appendChild(addBtn);
  }
  function startAddTag(id, wrap, addBtn) {
    addBtn.hidden = true;
    const input = document.createElement('input');
    input.className = 'tag-input'; input.placeholder = 'tag…'; input.setAttribute('list', 'tag-suggestions');
    wrap.appendChild(input); input.focus();
    let committed = false;
    const commit = () => {
      if (committed) return; committed = true;
      const val = input.value.trim().toLowerCase();
      if (val) addTag(id, val); else { addBtn.hidden = false; input.remove(); }
    };
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') { e.preventDefault(); commit(); }
      else if (e.key === 'Escape') { committed = true; addBtn.hidden = false; input.remove(); }
    });
    input.addEventListener('blur', commit);
  }

  // ================= mutations =================
  function addTag(id, tag) {
    const list = tagStore[id] ? [...tagStore[id]] : [];
    if (!list.includes(tag)) list.push(tag);
    list.sort((a, b) => a.localeCompare(b));
    tagStore[id] = list; saveTags();
    renderFilters();
    if (cardEls.has(id)) renderCardTags(id);
  }
  function removeTag(id, tag) {
    if (!tagStore[id]) return;
    tagStore[id] = tagStore[id].filter((t) => t !== tag);
    if (!tagStore[id].length) delete tagStore[id];
    saveTags();
    if (!allCustomTags().includes(tag)) filters.tags.delete(tag);
    renderFilters();
    if (cardEls.has(id)) renderCardTags(id);
  }
  function toggleFav(id) {
    favorites.has(id) ? favorites.delete(id) : favorites.add(id);
    saveFavs();
    const refs = cardEls.get(id);
    if (refs) {
      const on = favorites.has(id);
      refs.star.classList.toggle('on', on);
      refs.star.textContent = on ? '★' : '☆';
    }
    dom.favCount.textContent = favorites.size;
    if (filters.favOnly) renderGrid(); // card may need to disappear/appear
  }
  function toggleSelect(id, on) {
    on ? selection.add(id) : selection.delete(id);
    const refs = cardEls.get(id);
    if (refs) { refs.root.classList.toggle('selected', on); refs.checkbox.checked = on; }
    updateBulkBar();
  }
  function updateBulkBar() {
    const n = selection.size;
    dom.bulkBar.hidden = n === 0;
    dom.bulkCount.textContent = `${n} selected`;
  }

  // ================= bulk actions =================
  function bulkAddTag() {
    const tag = dom.bulkTagInput.value.trim().toLowerCase();
    if (!tag || !selection.size) return;
    for (const id of selection) addTagSilent(id, tag);
    saveTags(); dom.bulkTagInput.value = '';
    render();
  }
  function bulkRemoveTag() {
    const tag = dom.bulkTagInput.value.trim().toLowerCase();
    if (!tag || !selection.size) return;
    for (const id of selection) {
      if (tagStore[id]) {
        tagStore[id] = tagStore[id].filter((t) => t !== tag);
        if (!tagStore[id].length) delete tagStore[id];
      }
    }
    saveTags(); dom.bulkTagInput.value = '';
    if (!allCustomTags().includes(tag)) filters.tags.delete(tag);
    render();
  }
  function addTagSilent(id, tag) {
    const list = tagStore[id] ? [...tagStore[id]] : [];
    if (!list.includes(tag)) list.push(tag);
    list.sort((a, b) => a.localeCompare(b));
    tagStore[id] = list;
  }
  function bulkSetFav(on) {
    if (!selection.size) return;
    for (const id of selection) on ? favorites.add(id) : favorites.delete(id);
    saveFavs(); render();
  }
  function bulkSelectVisible() {
    for (const s of sounds.filter(matches)) selection.add(s.id);
    render(); updateBulkBar();
  }
  function bulkClear() { selection.clear(); render(); updateBulkBar(); }

  // ================= browser analysis (non-WAV) =================
  let audioCtx = null;
  function analyzePending() {
    const pending = sounds.filter((s) => analysis[s.id] && analysis[s.id].peaks == null);
    if (!pending.length) return;
    let i = 0, active = 0;
    const CONCURRENCY = 3;
    const next = () => {
      while (active < CONCURRENCY && i < pending.length) {
        const s = pending[i++]; active++;
        analyzeOne(s).finally(() => { active--; next(); });
      }
    };
    next();
  }
  async function analyzeOne(s) {
    try {
      if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)();
      const res = await fetch(s.src);
      const arr = await res.arrayBuffer();
      const buf = await audioCtx.decodeAudioData(arr);
      const N = 160, peaks = new Array(N).fill(0);
      let globalPeak = 0, sumSq = 0, count = 0;
      const frames = buf.length, ch = buf.numberOfChannels;
      const chans = [];
      for (let c = 0; c < ch; c++) chans.push(buf.getChannelData(c));
      for (let f = 0; f < frames; f++) {
        const bin = Math.min(N - 1, Math.floor((f * N) / frames));
        let frameMax = 0;
        for (let c = 0; c < ch; c++) {
          const v = chans[c][f]; const av = Math.abs(v);
          if (av > frameMax) frameMax = av;
          if (av > globalPeak) globalPeak = av;
          sumSq += v * v; count++;
        }
        if (frameMax > peaks[bin]) peaks[bin] = frameMax;
      }
      const rms = count ? Math.sqrt(sumSq / count) : 0;
      const toDb = (x) => (x > 0 ? Math.round(20 * Math.log10(x) * 10) / 10 : null);
      const data = {
        duration: Math.round(buf.duration * 1000) / 1000,
        peakDb: toDb(globalPeak), rmsDb: toDb(rms),
        peaks: peaks.map((p) => Math.round(p * 1000) / 1000),
      };
      analysis[s.id] = data;
      analysisCache[s.id] = data; saveJSON(ANALYSIS_KEY, analysisCache);
      updateCardMeta(s.id); drawWaveform(s.id, 0);
      renderFiltersDebounced();
    } catch { /* file:// or undecodable — leave placeholder */ }
  }
  let filtersTimer = null;
  function renderFiltersDebounced() {
    if (filtersTimer) clearTimeout(filtersTimer);
    filtersTimer = setTimeout(() => { filtersTimer = null; renderFilters(); }, 400);
  }

  // ================= export / import =================
  function exportData() {
    const payload = { tags: tagStore, favorites: [...favorites] };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'library-data.json'; a.click();
    URL.revokeObjectURL(url);
  }
  function applyData(data, opts) {
    if (!data || typeof data !== 'object') return;
    const remote = opts && opts.remote; // loaded from gist/file — don't schedule a push back
    if (remote) suppressSync = true;
    if (data.tags && typeof data.tags === 'object') tagStore = data.tags;
    else if (!Array.isArray(data.favorites)) tagStore = data; // legacy: flat tag map
    if (Array.isArray(data.favorites)) favorites = new Set(data.favorites);
    saveTags(); saveFavs(); render();
    if (remote) suppressSync = false;
  }
  function importData(file) {
    const reader = new FileReader();
    reader.onload = () => {
      try { applyData(JSON.parse(reader.result)); alert('Library data imported.'); }
      catch { alert('Could not parse that file as JSON.'); }
    };
    reader.readAsText(file);
  }
  async function seedFromFile() {
    if (Object.keys(tagStore).length || favorites.size) return;
    try {
      const res = await fetch(DATA_FILE, { cache: 'no-store' });
      if (!res.ok) return;
      applyData(await res.json(), { remote: true });
    } catch { /* file:// or no file — fine */ }
  }

  // ================= gist sync =================
  const SYNC_DEBOUNCE_MS = 5 * 60 * 1000; // batch edits; push ~5 min after the last one
  let credentials = GistStore.getCredentials();
  let syncState = 'local';   // local | synced | pending | saving | saved | error
  let suppressSync = false;  // true while applying remote data
  let syncTimer = null;

  const currentData = () => ({ tags: tagStore, favorites: [...favorites] });

  // Called from saveTags()/saveFavs() — the single chokepoint for every tag/favorite change.
  function markDirty() {
    if (suppressSync || !credentials) return;
    GistStore.setPending();
    setSyncState('pending');
    clearTimeout(syncTimer);
    syncTimer = setTimeout(pushToGist, SYNC_DEBOUNCE_MS);
  }

  async function pushToGist() {
    if (!credentials) return;
    clearTimeout(syncTimer);
    setSyncState('saving');
    try {
      await GistStore.saveToGist(credentials.token, credentials.gistId, currentData());
      GistStore.clearPending();
      setSyncState('saved');
      setTimeout(() => { if (syncState === 'saved') setSyncState('synced'); }, 2500);
    } catch (e) {
      setSyncState('error', e.message);
    }
  }

  function setSyncState(state, msg) {
    syncState = state;
    const map = {
      local: ['Local only', 'local'],
      synced: ['Synced ✓', 'ok'],
      saved: ['Saved ✓', 'ok'],
      pending: ['Unsynced changes', 'pending'],
      saving: ['Syncing…', 'saving'],
      error: ['Sync error — retry', 'error'],
    };
    const [text, cls] = map[state] || ['', ''];
    dom.syncStatus.textContent = text;
    dom.syncStatus.className = 'sync-status ' + cls;
    dom.syncStatus.title = msg || (credentials ? `Gist ${credentials.gistId}` : 'Not connected');
  }

  function updateConnectedUI() {
    const connected = !!credentials;
    dom.syncConnectView.hidden = connected;
    dom.syncConnectedView.hidden = !connected;
    if (connected) {
      dom.gistLink.textContent = credentials.gistId;
      dom.gistLink.href = 'https://gist.github.com/' + credentials.gistId;
    }
  }
  function openSyncModal() { updateConnectedUI(); showSyncError(''); dom.syncModal.hidden = false; }
  function closeSyncModal() { dom.syncModal.hidden = true; }
  function showSyncError(msg) { dom.syncError.textContent = msg || ''; dom.syncError.hidden = !msg; }

  async function handleConnect() {
    const token = dom.gistToken.value.trim();
    if (!token) return showSyncError('Token is required.');
    const mode = document.querySelector('input[name="gistmode"]:checked').value;
    dom.gistConnect.disabled = true; showSyncError('');
    try {
      let gistId;
      if (mode === 'new') {
        gistId = await GistStore.createGist(token, currentData()); // uploads current local data
      } else {
        gistId = GistStore.extractGistId(dom.gistId.value);
        if (!gistId) throw new Error('Gist ID is required.');
        applyData(await GistStore.loadFromGist(token, gistId), { remote: true }); // remote wins on connect
      }
      credentials = { token, gistId };
      GistStore.saveCredentials(token, gistId);
      GistStore.clearPending();
      dom.gistToken.value = '';
      updateConnectedUI();
      setSyncState('synced');
      closeSyncModal();
    } catch (e) {
      showSyncError(e.message);
    } finally {
      dom.gistConnect.disabled = false;
    }
  }

  function handleDisconnect() {
    if (!confirm('Disconnect from GitHub? Your tags & favorites stay saved on this device.')) return;
    GistStore.clearCredentials(); GistStore.clearPending();
    credentials = null;
    clearTimeout(syncTimer);
    updateConnectedUI();
    setSyncState('local');
    closeSyncModal();
  }

  async function handlePull() {
    if (!credentials) return;
    if (!confirm('Reload from gist? This replaces the tags & favorites on this device.')) return;
    setSyncState('saving');
    try {
      applyData(await GistStore.loadFromGist(credentials.token, credentials.gistId), { remote: true });
      GistStore.clearPending();
      setSyncState('synced');
      closeSyncModal();
    } catch (e) {
      setSyncState('error', e.message);
    }
  }

  // ================= events =================
  dom.search.addEventListener('input', () => { filters.search = dom.search.value.trim().toLowerCase(); renderGrid(); });
  dom.sort.addEventListener('change', () => { sortMode = dom.sort.value; renderGrid(); });
  dom.tagMatchMode.addEventListener('change', () => { filters.tagMatchAll = dom.tagMatchMode.checked; renderGrid(); });
  dom.favToggle.addEventListener('click', () => { filters.favOnly = !filters.favOnly; render(); });
  dom.clearBtn.addEventListener('click', () => {
    filters.search = ''; dom.search.value = '';
    filters.games.clear(); filters.lengths.clear(); filters.tags.clear(); filters.favOnly = false;
    render();
  });
  dom.exportBtn.addEventListener('click', exportData);
  dom.importInput.addEventListener('change', (e) => { if (e.target.files[0]) importData(e.target.files[0]); e.target.value = ''; });
  dom.bulkAdd.addEventListener('click', bulkAddTag);
  dom.bulkRemove.addEventListener('click', bulkRemoveTag);
  dom.bulkStar.addEventListener('click', () => bulkSetFav(true));
  dom.bulkUnstar.addEventListener('click', () => bulkSetFav(false));
  dom.bulkSelectVisible.addEventListener('click', bulkSelectVisible);
  dom.bulkClear.addEventListener('click', bulkClear);
  dom.bulkTagInput.addEventListener('keydown', (e) => { if (e.key === 'Enter') bulkAddTag(); });
  window.addEventListener('resize', () => { for (const id of cardEls.keys()) drawWaveform(id, 0); });

  // sync events
  dom.syncBtn.addEventListener('click', openSyncModal);
  dom.syncClose.addEventListener('click', closeSyncModal);
  dom.syncModal.addEventListener('click', (e) => { if (e.target === dom.syncModal) closeSyncModal(); });
  dom.syncStatus.addEventListener('click', () => {
    if (syncState === 'error' && credentials) pushToGist(); else openSyncModal();
  });
  dom.gistConnect.addEventListener('click', handleConnect);
  dom.gistDisconnect.addEventListener('click', handleDisconnect);
  dom.gistSyncNow.addEventListener('click', pushToGist);
  dom.gistPull.addEventListener('click', handlePull);
  document.querySelectorAll('input[name="gistmode"]').forEach((r) => r.addEventListener('change', () => {
    dom.gistId.hidden = document.querySelector('input[name="gistmode"]:checked').value !== 'existing';
  }));

  // ================= boot =================
  render();
  updateBulkBar();
  analyzePending();
  updateConnectedUI();

  (async function boot() {
    if (!credentials) { setSyncState('local'); seedFromFile(); return; }
    setSyncState(GistStore.hasPending() ? 'pending' : 'saving');
    try {
      const remote = await GistStore.loadFromGist(credentials.token, credentials.gistId);
      if (GistStore.hasPending()) {
        // Lean last-write-wins: this device has unsynced edits (the newest), so push them.
        pushToGist();
      } else {
        applyData(remote, { remote: true });
        setSyncState('synced');
      }
    } catch (e) {
      setSyncState('error', e.message); // keep local/committed data as fallback
    }
  })();
})();
